# Generated by Django 3.1.7 on 2021-03-08 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 8, 20, 0, 46, 965865, tzinfo=utc)),
        ),
    ]
