# Generated by Django 3.1.7 on 2021-03-09 22:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210308_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 3, 9, 22, 8, 55, 965107, tzinfo=utc)),
        ),
    ]
